## Ejercicios Numpy 

In [25]:
import numpy as np, pandas as pd

#### 1. Crea una matriz 4*4 rellena con el valor 0.5

In [67]:
matriz_1 = np.full((4,4),0.5)
print(matriz_1)

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 2. Crea una matriz 6*6 con unos en los bordes y 0 en el interior (utilizando slicing)

In [26]:
matriz = np.ones((6, 6), dtype=int)
matriz[1:-1, 1:-1] = 0

print(matriz)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 3. Crea una matriz de numpy 3*2 a partir de una lista de listas de números float

In [41]:
lista = [[1.0,3.2], [3.5,9.3], [0.5, 4.6]]

matriz = np.array(lista)
matriz

array([[1. , 3.2],
       [3.5, 9.3],
       [0.5, 4.6]])

#### 4. Divide entre 4 los valores de la columna 1

In [42]:
matriz[:, 0] /= 4
matriz

array([[0.25 , 3.2  ],
       [0.875, 9.3  ],
       [0.125, 4.6  ]])

#### 5. Calcula la media de los elementos de las primeras dos primeras filas

In [50]:
np.average(matriz[0:2,:])

np.float64(3.40625)

#### 6. Crea una matriz aletoria de 4*4 con valores en [0, 1) 

El módulo <code>random</code> de numpy sirve para generar números aleatorios. En él tenemos varias funciones entre ellas <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html">rand</a>



In [70]:
matriz_6 = np.random.randint(0,2, size=(4,4))
print(matriz_6)

[[0 0 1 1]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 0]]


#### 7.  Muestra la suma, media y desviación de los elementos de la matriz del ejercicio 1 

In [69]:
suma = matriz_1.sum()
print(f"Suma: {suma}")

media = matriz_1.mean()
print(f"Media: {media}")

desviacion = matriz_1.std()
print(f"Desviacion: {desviacion}")

Suma: 8.0
Media: 0.5
Desviacion: 0.0


#### 8. Ordena por filas la matriz del ejercicio 1

In [72]:
matriz_1.sort(axis=1)
print(matriz_1)

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 9. Multiplica las matrices del ejercio 1 y 6

In [71]:
result = matriz_1 * matriz_6
print(result)

[[0.  0.  0.5 0.5]
 [0.5 0.5 0.  0.5]
 [0.5 0.5 0.5 0. ]
 [0.5 0.5 0.5 0. ]]


#### 10. Prueba a concatenar las matrices de los ejercicios 1 y 6 en vertical y horizontal

Echa un vistazo al apartado 2 del siguiente <a href="https://rmoralesdelgado.com/all/numpy-concatenate-r_-c_/"> link </a> donde explica el uso de <a href="https://numpy.org/doc/stable/reference/generated/numpy.c_.html">numpy.c_ </a> y <a href="https://numpy.org/doc/stable/reference/generated/numpy.r_.html">numpy.r_</a>

Fíjate también en <code>%%timeit</code> que se usa en Jupyter notebooks para medir el tiempo de ejecución de un bloque de código