<center>
<h1 style="color: #√;">Python</h1> 
<h3 style="color: #333333;">Ejercicios Numpy, Pandas y gráficos</h3> 
</center>

<br>


#### Autor: escribir aquí el nombre del autor


<h2 style="color: #007BC4;">Numpy</h2>
<hr style="border: 0.5px solid #007BC4;">

El array de numpy <code>gdp_2016</code> contiene el producto interior bruto de países del mundo en el año 2016, en dólares. 



In [11]:
import numpy as np
import pandas as pd

#para conseguir el array a partir de un Dataframe podemos utilizar .values o to_numpy(), esta última es más moderna 
#gdp_2016 = pd.read_csv("data/gdp_pc.csv")["2016"].values
gdp_2016 = pd.read_csv("data/gdp_pc.csv")["2016"].to_numpy()

gdp_2016[0:10] # visualizamos los 10 primeros valores del array

array([           nan,  1944.11700491,  6454.13537039, 11540.02556108,
                  nan, 16726.72218488, 72399.65347339, 19939.93077479,
        8832.76343477,            nan])

#### Utilizando operaciones lógicas sobre este array, realiza los siguientes ejercicios:


#### 1 -  Crea un nuevo array sin los elementos que son NaN

In [21]:
serie_filtrada_Nan = gdp_2016[~np.isnan(gdp_2016)]
serie_filtrada_Nan

<class 'numpy.ndarray'>


array([  1944.11700491,   6454.13537039,  11540.02556108,  16726.72218488,
        72399.65347339,  19939.93077479,   8832.76343477,  22661.48853616,
        46012.32845157,  50551.5531752 ,  17256.62697044,    777.75285166,
        46428.67142458,   2167.64282343,   1771.01528722,   3579.75679135,
        19242.62261574,  22516.81648228,  12172.06646607,  18066.3006624 ,
         8461.53565294,   7234.19524335,  15123.85001428,  18064.60442722,
        77420.61217204,   8900.76455309,  16956.72477025,    698.70665573,
        44819.48360027,  26851.1685408 ,  63888.73238665,  23193.97411052,
        15529.08410645,   3693.43690912,   3609.37559695,    801.63011974,
         5717.29037095,  14153.92792519,   1521.85721808,   6551.31894829,
        16609.73935418,  15370.63489842,  32707.872887  ,  34749.21236327,
        48860.52529211,  10947.71518781,  49029.01483891,  15204.93246446,
        15013.29637986,  13839.96863584,   9175.64442097,  17025.39067931,
        19516.08298373,  

#### 2 -  Selecciona aquellos PIB que son mayores que 50.000$

In [22]:
serie_filtrada_50k = gdp_2016[gdp_2016 > 50000]
serie_filtrada_50k

array([ 72399.65347339,  50551.5531752 ,  77420.61217204,  63888.73238665,
        58617.97062639,  71472.29596487,  50745.68297711,  74263.99862606,
       102389.43772763, 105420.41423718,  56344.96375629,  50538.6065696 ,
        58790.06140389, 127480.48251099,  54416.61249319,  87832.58651422,
        60932.93003722,  57638.15908799])

#### 3 -  Selecciona aquellos PIB que son menores que 5.000$

In [23]:
serie_filtrada_5k = gdp_2016[gdp_2016 < 5000]
serie_filtrada_5k

array([1944.11700491,  777.75285166, 2167.64282343, 1771.01528722,
       3579.75679135,  698.70665573, 3693.43690912, 3609.37559695,
        801.63011974, 1521.85721808, 1734.46407452, 4254.34870787,
       3508.71519196, 4292.44889992, 1966.37968826, 1676.86477284,
       1608.70437903, 4736.83914255, 2270.13030428, 1783.71512959,
       3627.9834637 , 2834.05481866, 3155.11426394, 3552.09178948,
       3736.96461203, 2108.53722771,  812.67394381, 2622.06907623,
       1701.37258736, 2951.02189398, 1506.23832521, 4022.97863242,
       2125.71602653, 1216.79278744, 3852.52590437, 1168.82562558,
        986.20696062, 2477.9033451 , 4182.53934131, 3775.07502387,
       1912.90118206, 4730.46186883, 2566.11917856, 2235.3146905 ,
       1476.21371969, 3721.66067336, 3723.92091102, 3237.3925436 ,
       1990.72665731, 1490.53623573, 2979.31023902, 2140.35737389,
       3723.92091102, 3651.02148404, 2786.2722427 , 1819.43435088,
       3080.56575434, 2507.47166249, 3933.06646044, 2027.08491

#### 4 -  Selecciona aquellos PIB que se encuentran entre 40.000 y 50.000

In [30]:
serie_filtrada_5k = gdp_2016[gdp_2016 < 50000]
serie_filtrada_5k[serie_filtrada_5k > 40000]

array([46012.32845157, 46428.67142458, 44819.48360027, 48860.52529211,
       49029.01483891, 42063.79406454, 43378.14602882, 41343.29253554,
       42656.2166022 , 46864.95679091, 42281.18818958, 41885.92611335,
       44804.46017271, 48904.55437072])

<h2 style="color: #007BC4;">Pandas y gráficos</h2>
<hr style="border: 0.5px solid #007BC4;">

El **dataset** que vamos a a utilizar para realizar los siguientes ejercicios se denomina **"tips"** (tips.csv en la carpeta data, descargado de Kaggle) y contiene los datos que un camarero registró sobre cada propina que recibió durante un período de unos meses trabajando en un restaurante.


### 1. Lee el dataset con pandas y cárgalo en un DataFrame

In [7]:
tips = pd.read_csv("data/tipos.csv").to_numpy()

### 2. Muestra por pantalla las primeras filas del DataFrame

### 3. Muestra la forma del DataFrame

### 4. Obtén los datos de la columna **total_bill**

### 5. Genera una gráfica de barras donde se muestren el número propinas por día (con matplotlib o seaborn). 

### 6. Crea una gráfica **scatter** entre **total_bill** y **tip** utilizando matplotlib o seaborn. 

### 7. Asigna un color a los puntos en base a la variable "sex" (muéstralo en la leyenda)

### 8. Muestra ambas gráficas en una única figura con subplots.

Ejemplo de resultado (es orientativo, no tiene que ser exactamente igual):

<img src="img/graficas.png" style="max-width: 600px">
